backend:
  name: git-gateway
  branch: master

media_folder: /src/style/images

collections:
  - name: "sidebar"
    label: "Sidebar"
    folder: "content/sidebar"
    create: true
    fields:
      - {
          label: "Salon name",
          name: "salonName",
          widget: "string",
          default: "VUK Nails",
        }
      - {
          label: "Address",
          name: "address",
          widget: "string",
          default: "Ленинский проспект",
        }
      - {
          label: "Working days",
          name: "workingDays",
          widget: "string",
          default: "Пн-Вс",
        }
      - {
          label: "Working hours",
          name: "workingHours",
          widget: "string",
          default: "10:00-20:00",
        }
      - {
          label: "Contact phone",
          name: "contactTelephone",
          widget: "string",
          default: "+7(929)924-34-37",
        }
      - {
          label: "Instagram URL",
          name: "instagramURL",
          widget: "string",
          default: "https://www.instagram.com/vuk_nails/",
        }
      - {
          label: "Facebook URL",
          name: "facebookURL",
          widget: "string",
          default: "https://www.facebook.com/VUK-NAILS-104670354667176/",
        }

  - name: "frontpage"
    label: "Frontpage"
    folder: "content/frontpage"
    create: true
    fields:
      - {
          label: "Frontpage Heading",
          name: "frontpageHeading",
          widget: "string",
          default: "Красота без фильтров в VUK Nails!",
        }
      - {
          label: "Front page Image #1",
          name: "frontImageOne",
          widget: "image",
          default: "/images/hero_1.jpg",
          allow_multiple: false,
        }
      - {
          label: "Front page Image #2",
          name: "frontImageTwo",
          widget: "image",
          default: "/images/hero_2.jpg",
          allow_multiple: false,
        }
      - {
          label: "Front page Image #3",
          name: "frontImageThree",
          widget: "image",
          default: "/images/hero_3.jpg",
          allow_multiple: false,
        }
      - {
          label: "Front page Image #4",
          name: "frontImageFour",
          widget: "image",
          default: "/images/hero_4.jpg",
          allow_multiple: false,
        }
      - {
          label: "Front page Image #5",
          name: "frontImageFive",
          widget: "image",
          default: "/images/hero_5.jpg",
          allow_multiple: false,
        }

  - name: "about_us"
    label: "About us"
    folder: "content/about_us"
    create: true
    fields:
      - {
          label: "About us text",
          name: "aboutUsText",
          widget: "markdown",
          default:
            "Небольшая светлая студия красоты VUK Nails открылась в новом доме ЖК The MID по адресу Ленинский проспект 95Б в конце июня 2020 года.

            Профессиональные мастера быстро и качественно окажут вам следующие услуги:

            маникюр
            педикюр
            уход за волосами
            укладки
            брови
            Мы гарантируем вам безопасность и приятное времяпровождение.
            ",
        }
      - {
          label: "Owner photo",
          name: "ownerPhoto",
          widget: "image",
          default: "/images/olga.jpg",
          allow_multiple: false,
        }

  - name: "team"
    label: "Team"
    folder: "content/team"
    create: true
    fields:
      - {
          label: "Name of employee",
          name: "employee_name",
          widget: "string",
          default: "Надежда",
        }
      - {
          label: "Employee profession Primary",
          name: "employee_profession_primary",
          widget: "string",
          default: "Мастер маникюра/педикюра",
        }
      - {
          label: "Employee profession Secondary",
          name: "employee_profession_secondary",
          widget: "string",
          default: "Бровист",
        }
      - {
          label: "Employee picture",
          name: "employeePicture",
          widget: "image",
          default: "/images/nadezhda.jpg",
          allow_multiple: false,
        }

  - name: "services"
    label: "Our Services"
    folder: "content/services"
    create: true
    fields:
      - {
          label: "Service #1",
          name: "serviceOne",
          widget: "string",
          default: "Маникюр",
        }
      - {
          label: "Service #2",
          name: "serviceTwo",
          widget: "string",
          default: "Педикюр",
        }
      - {
          label: "Service #3",
          name: "serviceThree",
          widget: "string",
          default: "Брови",
        }
      - {
          label: "Service #4",
          name: "serviceFour",
          widget: "string",
          default: "Уход за волосами",
        }
      - {
          label: "Service #1 picture",
          name: "serviceOnePic",
          widget: "image",
          default: "/images/services_2.jpg",
          allow_multiple: false,
        }
      - {
          label: "Service #2 picture",
          name: "serviceTwoPic",
          widget: "image",
          default: "/images/services_4.jpg",
          allow_multiple: false,
        }
      - {
          label: "Service #3 picture",
          name: "serviceThreePic",
          widget: "image",
          default: "/images/services_3.jpg",
          allow_multiple: false,
        }
      - {
          label: "Service #4 picture",
          name: "serviceFourPic",
          widget: "image",
          default: "/images/services_1.jpg",
          allow_multiple: false,
        }

  - name: "contact"
    label: "Contact"
    folder: "content/contact"
    create: true
    fields:
      - {
          label: "Telephone",
          name: "contact_phone",
          widget: "string",
          default: "+7(929)924-34-37",
        }
      - {
          label: "Address",
          name: "contact_address",
          widget: "string",
          default: "ул. Ленинский проспект, д. 96 Б
            ",
        }
      - {
          label: "E Mail",
          name: "contact_email",
          widget: "string",
          default: "vuknailslp@gmail.com",
        }
      - {
          label: "Working Days",
          name: "contact_days",
          widget: "string",
          default: "Пн-Вс",
        }
      - {
          label: "Working Hours",
          name: "contact_hours",
          widget: "string",
          default: "10:00-20:00",
        }

  - name: "products"
    label: "Our Products"
    folder: "content/products"
    create: true
    fields:
      - {
          label: "Brand pictures",
          name: "brand_pictures",
          widget: "list",
          field:
            {
              label: "image",
              name: "image",
              widget: "image",
              allow_multiple: true,
            },
        }

  - name: "prices"
    label: "Service Prices"
    folder: "content/prices"
    create: true
    widget: "list"
    fields:
      - {
          label: "Manicure prices",
          name: "manicure_prices",
          widget: "list",
          fields:
            - {label: "manicure service name", name: "manicure_key", widget: "string"}
            - {label: "manicure service value (in RUB)", name: "manicure_value", widget: "string"}
        }
      - {
          label: "Pedicure prices",
          name: "pedicure_prices",
          widget: "list",
          fields:
            - {label: "pedicure service name", name: "pedicure_key", widget: "string"}
            - {label: "pedicure service value (in RUB)", name: "pedicure_value", widget: "string"}
        }
      - {
          label: "Brovi prices",
          name: "brovi_prices",
          widget: "list",
          fields:
            - {label: "brovi service name", name: "brovi_key", widget: "string"}
            - {label: "brovi service value (in RUB)", name: "brovi_value", widget: "string"}
        }
      - {
          label: "Uhodi prices",
          name: "uhodi_prices",
          widget: "list",
          fields:
            - {label: "uhodi service name", name: "uhodi_key", widget: "string"}
            - {label: "uhodi service value (in RUB)", name: "uhodi_value", widget: "string"}
        }